import React, { useMemo, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { useStore } from '../store';
import { allExercises, BODYPARTS, equipmentOf } from '../lib/exercises';
import { MUSCLE_NAME, musclesOf } from '../lib/muscles';
import { defaultConfig } from '../lib/history';
import { bestWeightFor } from '../lib/history';
import { fmtNum, uid } from '../lib/format';
import { t } from '../lib/i18n';
import { ExerciseConfig, ExerciseDetail, ExerciseRow, useExerciseSearch } from '../components/exercises';
import BodyMap from '../components/BodyMap';
import { AppText, Button, Card, Chip, Header, IconButton, Input, Screen, useColors } from '../components/ui';

export default function LibraryScreen() {
  const { S, update } = useStore(); const colors = useColors(); const [query, setQuery] = useState(''); const [muscles, setMuscles] = useState(new Set()); const [showMap, setShowMap] = useState(false); const [equipment, setEquipment] = useState(''); const [shown, setShown] = useState(40); const [detail, setDetail] = useState(null); const [addExercise, setAddExercise] = useState(null); const [addRoutine, setAddRoutine] = useState(null); const [custom, setCustom] = useState(false); const [customEdit, setCustomEdit] = useState(null); const [customName, setCustomName] = useState(''); const [customPart, setCustomPart] = useState('other');
  const base = useExerciseSearch(S, query, muscles); const equipmentOptions = equipmentOf(base); const activeEquipment = equipmentOptions.includes(equipment) ? equipment : ''; const list = activeEquipment ? base.filter(exercise => exercise.eq === activeEquipment) : base;
  const toggleMuscle = value => { setMuscles(prev => { const next = new Set(prev); next.has(value) ? next.delete(value) : next.add(value); return next; }); setEquipment(''); setShown(40); };
  const createCustom = () => { const name = customName.trim(); if (!name) return; const exercise = customEdit ? { ...customEdit, n: name, bp: customPart, tg: customPart } : { id: `custom-${uid()}`, n: name, bp: customPart, tg: customPart, eq: 'other', sm: [], st: [] }; update(state => { if (customEdit) state.customEx = state.customEx.map(item => item.id === customEdit.id ? exercise : item); else state.customEx.unshift(exercise); }); setCustom(false); setCustomEdit(null); setCustomName(''); setDetail(exercise); };
  const editCustom = exercise => { setDetail(null); setCustomEdit(exercise); setCustomName(exercise.n); setCustomPart(exercise.bp); setCustom(true); };
  const deleteCustom = exercise => Alert.alert(t('Delete exercise?'), t('This removes it from your library and routines.'), [{ text: t('Cancel') }, { text: t('Delete'), style: 'destructive', onPress: () => { update(state => { state.customEx = state.customEx.filter(item => item.id !== exercise.id); state.routines.forEach(routine => { routine.ex = routine.ex.filter(item => item.id !== exercise.id); }); }); setDetail(null); } }]);
  return <Screen><Header title={t('Exercises')} subtitle={t('{0} exercises with animations', list.length)} /><View style={{ flexDirection: 'row', gap: 8, marginBottom: 12 }}><Input style={{ flex: 1 }} placeholder={t('Search…')} value={query} onChangeText={value => { setQuery(value); setShown(40); }} /><IconButton name={showMap ? 'filter-remove' : 'filter'} onPress={() => setShowMap(v => !v)} color={(muscles.size > 0 || activeEquipment) ? colors.accent : undefined} /></View>{muscles.size > 0 ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{[...muscles].map(m => <Chip key={m} title={`× ${t(MUSCLE_NAME[m])}`} active onPress={() => toggleMuscle(m)} />)}</ScrollView> : null}{showMap ? <Card style={styles.muscleCard}><AppText muted style={{ fontSize: 12 }}>{t('Tap muscles to filter — multiple selections show exercises matching any')}</AppText><BodyMap body={S.body} selected={muscles} onMuscle={toggleMuscle} />{equipmentOptions.length > 1 ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.chips, { marginTop: 8 }]}><Chip title={t('Any equipment')} active={!activeEquipment} onPress={() => setEquipment('')} />{equipmentOptions.map(value => <Chip key={value} title={t(value)} active={activeEquipment === value} onPress={() => setEquipment(value)} />)}</ScrollView> : null}</Card> : null}
    <Card style={{ paddingVertical: 0 }}><ExerciseRow exercise={{ n: t('Create your own exercise'), bp: t('Custom'), tg: t('name + body part'), eq: '' }} onPress={() => { setCustomEdit(null); setCustomName(''); setCustom(true); }} />{list.slice(0, shown).map(exercise => <ExerciseRow key={exercise.id} exercise={exercise} fullName onPress={() => setDetail(exercise)} accessory={<View style={styles.accessory}>{bestWeightFor(S, exercise.id) > 0 ? <AppText style={{ color: colors.accent, fontWeight: '800' }}>{fmtNum(bestWeightFor(S, exercise.id))}</AppText> : null}<Button compact title={t('Plan')} icon="plus" onPress={() => setAddExercise(exercise)} /></View>} />)}</Card>{list.length > shown ? <Button title={t('Show more')} onPress={() => setShown(value => value + 40)} /> : null}
    <ExerciseDetail exercise={detail} visible={!!detail} onClose={() => setDetail(null)} footer={detail ? <View style={{ gap: 8 }}><Button title={t('Add to plan')} icon="plus" primary onPress={() => { setAddExercise(detail); setDetail(null); }} />{detail.id.startsWith('custom-') ? <><Button title={t('Edit exercise')} onPress={() => editCustom(detail)} /><Button title={t('Delete exercise')} danger onPress={() => deleteCustom(detail)} /></> : null}</View> : null} />
    <RoutineChooser exercise={addRoutine ? null : addExercise} routines={S.routines} close={() => setAddExercise(null)} choose={routine => { setAddRoutine(routine); }} />
    <ExerciseConfig exercise={addExercise} visible={!!addRoutine && !!addExercise} onClose={() => { setAddRoutine(null); setAddExercise(null); }} onSave={config => { update(state => state.routines.find(item => item.id === addRoutine.id).ex.push({ id: addExercise.id, ...config })); setAddRoutine(null); setAddExercise(null); }} />
    <Modal transparent visible={custom} animationType="fade" onRequestClose={() => setCustom(false)}><View style={styles.overlay}><View style={[styles.dialog, { backgroundColor: colors.surface }]}><AppText style={{ fontSize: 22, fontWeight: '800' }}>{t(customEdit ? 'Edit exercise' : 'Create your own exercise')}</AppText><Input value={customName} onChangeText={setCustomName} placeholder={t('Exercise name')} /><ScrollView horizontal contentContainerStyle={styles.chips}>{BODYPARTS.map(value => <Chip key={value} title={t(value)} active={customPart === value} onPress={() => setCustomPart(value)} />)}</ScrollView><Button title={t(customEdit ? 'Save' : 'Create')} primary onPress={createCustom} /><Button title={t('Cancel')} onPress={() => setCustom(false)} /></View></View></Modal>
  </Screen>;
}
function RoutineChooser({ exercise, routines, close, choose }) { const colors = useColors(); if (!exercise) return null; return <Modal transparent visible animationType="fade" onRequestClose={close}><View style={styles.overlay}><View style={[styles.dialog, { backgroundColor: colors.surface }]}><AppText style={{ fontWeight: '800', fontSize: 21 }}>{t('Add to routine')}</AppText>{routines.length ? routines.map(routine => <Pressable key={routine.id} style={styles.routine} onPress={() => choose(routine)}><AppText>{routine.name}</AppText></Pressable>) : <AppText muted>{t('Create a routine first.')}</AppText>}<Button title={t('Cancel')} onPress={close} /></View></View></Modal>; }
const styles = StyleSheet.create({ chips: { gap: 8, paddingVertical: 4 }, muscleCard: { gap: 6 }, accessory: { flexDirection: 'row', alignItems: 'center', gap: 8 }, overlay: { flex: 1, backgroundColor: '#000a', padding: 22, justifyContent: 'center' }, dialog: { padding: 18, borderRadius: 18, gap: 12, maxHeight: '85%' }, routine: { minHeight: 48, justifyContent: 'center' } });
