import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { useStore, DEF } from '../store';
import { ACCENTS } from '../lib/format';
import { addStarterPlan } from '../lib/plans';
import { buildDemoState } from '../lib/demoSeed';
import { exportBackup, pickAppExport, pickBackup } from '../lib/backup';
import { mergeImport } from '../lib/import-csv';
import { syncReminders } from '../lib/reminders';
import { effortOf } from '../lib/history';
import { LANGS, t } from '../lib/i18n';
import { AppText, Button, Card, Chip, Header, IconButton, Input, Row, Screen, SectionTitle, Toggle, useColors } from '../components/ui';

export default function SettingsScreen({ navigation }) {
  const { S, update, replaceState } = useStore(); const colors = useColors(); const [message, setMessage] = useState('');
  const notify = value => { setMessage(value); setTimeout(() => setMessage(''), 2400); };
  const importData = async () => { try { const value = await pickBackup(); if (!value) return; Alert.alert(t('Import backup?'), t('This replaces all current data with the backup file.'), [{ text: t('Cancel') }, { text: t('Import'), style: 'destructive', onPress: () => { replaceState(value); notify(t('Backup imported')); } }]); } catch (error) { notify(`${t('Import failed')}: ${error.message}`); } };
  const importApp = async () => { try { const parsed = await pickAppExport(S.unit); if (!parsed) return; const count = parsed.kind === 'bodyweight' ? parsed.bodyweight.length : parsed.workouts.length; Alert.alert(t('Import from {0}?', parsed.source || t('another app')), t('{0} entries found. Existing dates will not be duplicated.', count), [{ text: t('Cancel') }, { text: t('Import'), onPress: () => { update(state => { mergeImport(state, parsed); }); notify(t('Import complete')); } }]); } catch (error) { notify(`${t('Import failed')}: ${error.message}`); } };
  const toggleReminder = async value => { const next = { ...S, reminder: { ...S.reminder, on: value } }; try { const allowed = await syncReminders(next); if (!allowed) return notify(t('Notification permission was not granted')); update(state => { state.reminder.on = value; }); } catch { notify(t('Could not change notification settings')); } };
  const loadDemo = () => { Alert.alert(t('Load demo data?'), t('This replaces all current data with 12 weeks of sample workouts and weight history.'), [{ text: t('Cancel') }, { text: t('Load demo data'), onPress: () => { replaceState(buildDemoState()); notify(t('Demo data loaded')); } }]); };
  const reset = () => Alert.alert(t('Reset everything?'), t('Deletes your plan, workouts and body weight on this device. This cannot be undone.'), [{ text: t('Cancel') }, { text: t('Delete everything'), style: 'destructive', onPress: () => replaceState(DEF) }]);
  return <Screen><Header title={t('Settings')} left={<IconButton name="chevron-left" onPress={() => navigation.goBack()} />} />{message ? <Card style={{ backgroundColor: `${colors.accent}22` }}><AppText style={{ color: colors.accent, textAlign: 'center', fontWeight: '700' }}>{message}</AppText></Card> : null}
    <SectionTitle>{t('Your data')}</SectionTitle><Card style={{ paddingVertical: 0 }}><Row icon="lock" title={t('All data stays on this phone')} subtitle={t('No account, no cloud — export a backup anytime.')} /></Card>
    <SectionTitle>{t('General')}</SectionTitle><Card><AppText muted style={styles.label}>{t('Language')}</AppText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{Object.entries(LANGS).map(([value, label]) => <Chip key={value} title={label} active={(S.lang || 'en') === value} onPress={() => update(state => { state.lang = value; })} />)}</ScrollView><AppText muted style={styles.label}>{t('Weight unit')}</AppText><View style={styles.chips}>{['kg', 'lb'].map(value => <Chip key={value} title={value} active={S.unit === value} onPress={() => update(state => { state.unit = value; })} />)}</View><AppText dim style={{ fontSize: 12 }}>{t('Switching units changes labels only; logged values are not converted.')}</AppText></Card>
    <SectionTitle>{t('During a workout')}</SectionTitle><Card><AppText muted style={styles.label}>{t('Rest timer')}</AppText><View style={styles.chips}>{[60, 90, 120, 150, 180].map(value => <Chip key={value} title={`${value}s`} active={S.restSec === value} onPress={() => update(state => { state.restSec = value; })} />)}</View><Row icon="weather-sunny" title={t('Keep screen awake')}><Toggle value={S.keepAwake !== false} onValueChange={value => update(state => { state.keepAwake = value; })} /></Row><Row icon="bell" title={t('Sounds')}><Toggle value={!!S.sound} onValueChange={value => update(state => { state.sound = value; })} /></Row><AppText muted style={styles.label}>{t('Effort per set')}</AppText><View style={styles.chips}>{['none', 'rir', 'rpe'].map(value => <Chip key={value} title={value === 'none' ? t('Off') : value.toUpperCase()} active={effortOf(S) === value} onPress={() => update(state => { state.effort = value; delete state.showRir; })} />)}</View></Card>
    <SectionTitle>{t('Notifications')}</SectionTitle><Card><Row icon="calendar-clock" title={t('Workout day reminder')} subtitle={t('Uses only local notifications on planned days.')}><Toggle value={!!S.reminder?.on} onValueChange={toggleReminder} /></Row>{S.reminder?.on ? <><AppText muted style={styles.label}>{t('Reminder time (24-hour)')}</AppText><Input value={S.reminder.time || '08:00'} onChangeText={value => update(state => { state.reminder.time = value; })} placeholder="08:00" /></> : null}</Card>
    <SectionTitle>{t('Appearance')}</SectionTitle><Card><AppText muted style={styles.label}>{t('Theme')}</AppText><View style={styles.chips}>{['dark', 'light'].map(value => <Chip key={value} title={t(value === 'dark' ? 'Dark' : 'Light')} active={S.theme === value} onPress={() => update(state => { state.theme = value; })} />)}</View><AppText muted style={styles.label}>{t('Body diagram')}</AppText><View style={styles.chips}>{['male', 'female'].map(value => <Chip key={value} title={t(value === 'male' ? 'Male' : 'Female')} active={S.body === value} onPress={() => update(state => { state.body = value; })} />)}</View><AppText muted style={styles.label}>{t('Accent color')}</AppText><View style={styles.swatches}>{Object.entries(ACCENTS).map(([name, color]) => <View key={name} style={[styles.swatchRing, S.accent === name && { borderColor: colors.text }]}><View onTouchEnd={() => update(state => { state.accent = name; })} style={[styles.swatch, { backgroundColor: color }]} /></View>)}</View></Card>
    <SectionTitle>{t('Data')}</SectionTitle><Card style={{ paddingVertical: 0 }}><Row icon="creation" title={t('Load starter plan (PPL)')} onPress={() => { update(addStarterPlan); notify(t('Starter plan loaded — Mon Push · Wed Pull · Fri Legs')); }} /><Row icon="database" title={t('Load demo data')} subtitle={t('Populates 12 weeks of workouts & body weight')} onPress={loadDemo} /><Row icon="swap-horizontal" title={t('Import from another app')} subtitle={t('FitNotes, Strong, Hevy, or Apple Health')} onPress={importApp} /><Row icon="upload" title={t('Import backup')} onPress={importData} /><Row icon="download" title={t('Export backup (JSON)')} onPress={() => exportBackup(S).then(() => notify(t('Backup exported'))).catch(error => notify(error.message))} /><Row icon="trash-can" danger title={t('Reset everything')} onPress={reset} /></Card><AppText dim style={{ textAlign: 'center', marginTop: 12, lineHeight: 20 }}>openGym · {t('free & open source (AGPL v3)')}\n{t('Offline-first · no account · no server')}</AppText>
  </Screen>;
}
const styles = StyleSheet.create({ label: { fontSize: 13, fontWeight: '700', marginTop: 5 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingVertical: 4 }, swatches: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, swatchRing: { width: 36, height: 36, borderRadius: 18, borderWidth: 2, borderColor: 'transparent', padding: 3 }, swatch: { flex: 1, borderRadius: 14 } });
