import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useStore } from '../store';
import { EXIDX } from '../lib/exercises';
import { bestWeightFor, lastBW, setLabel, streakWeeks, workoutVolume } from '../lib/history';
import { fmtDate, fmtNum, todayISO } from '../lib/format';
import { best1RM, e1rmSeries } from '../lib/onerm';
import { loadOfWorkouts, MUSCLE_NAME, rankOf } from '../lib/muscles';
import { t } from '../lib/i18n';
import Chart from '../components/Chart';
import { AppText, Card, Chip, Header, IconButton, Progress, Screen, SectionTitle, useColors } from '../components/ui';

export default function StatsScreen({ navigation }) {
  const { S } = useStore(); const colors = useColors(); const [exerciseId, setExerciseId] = useState(null);
  const exerciseIds = useMemo(() => [...new Set(S.workouts.flatMap(workout => workout.entries.map(entry => entry.id)))].filter(id => EXIDX[id]), [S.workouts]); const current = exerciseId && exerciseIds.includes(exerciseId) ? exerciseId : exerciseIds[0];
  const month = S.workouts.filter(workout => workout.d.slice(0, 7) === todayISO().slice(0, 7)).length; const weight = lastBW(S); const weight30 = S.bodyweight.filter(item => (item.t || new Date(item.d).getTime()) > Date.now() - 30 * 86400000); const delta = weight30.length > 1 ? weight30.at(-1).w - weight30[0].w : null;
  const topPoints = current ? S.workouts.flatMap(workout => { const entry = workout.entries.find(item => item.id === current); if (!entry) return []; const top = Math.max(0, ...entry.sets.filter(set => set.done).map(set => set.w || 0)); return top ? [{ y: top, d: workout.d }] : []; }) : [];
  const oneRm = current ? e1rmSeries(S, current) : []; const balance = rankOf(loadOfWorkouts(S.workouts.slice(-12))); const maxLoad = balance.worked.length ? loadOfWorkouts(S.workouts.slice(-12))[balance.worked[0]] : 1; const load = loadOfWorkouts(S.workouts.slice(-12));
  return <Screen><Header title={t('Stats')} subtitle={t('Progress & history')} right={<IconButton name="history" onPress={() => navigation.navigate('History')} />} /><View style={styles.tiles}><Tile icon="dumbbell" title={t('Workouts')} value={S.workouts.length} /><Tile icon="calendar" title={t('This month')} value={month} /><Tile icon="fire" title={t('Week streak')} value={streakWeeks(S)} /><Tile icon="scale" title={t('Weight 30d')} value={delta == null ? '—' : `${delta > 0 ? '+' : ''}${fmtNum(delta)} ${S.unit}`} /></View>
    <Card><AppText style={styles.cardTitle}>{t('Body weight')}</AppText><Chart points={S.bodyweight.map(item => ({ y: item.w }))} unit={S.unit} />{weight ? <AppText muted style={{ textAlign: 'center' }}>{fmtNum(weight.w)} {S.unit} · {fmtDate(weight.d, true)}</AppText> : null}</Card>
    {S.workouts.length ? <Card><AppText style={styles.cardTitle}>{t('Muscle balance')}</AppText><AppText muted style={{ marginBottom: 10 }}>{t('Last 12 workouts · by sets worked')}</AppText>{balance.worked.slice(0, 8).map(muscle => <View key={muscle} style={styles.barRow}><AppText style={{ width: 90, fontSize: 13 }}>{t(MUSCLE_NAME[muscle])}</AppText><View style={{ flex: 1 }}><Progress value={load[muscle] / maxLoad} /></View><AppText muted style={{ width: 30, textAlign: 'right', fontSize: 12 }}>{fmtNum(load[muscle])}</AppText></View>)}</Card> : null}
    <Card><AppText style={styles.cardTitle}>{t('Exercise progress')}</AppText>{exerciseIds.length ? <><View style={styles.chips}>{exerciseIds.slice(0, 12).map(id => <Chip key={id} title={EXIDX[id].n} active={current === id} onPress={() => setExerciseId(id)} />)}</View><AppText style={{ fontSize: 20, fontWeight: '800', textTransform: 'capitalize', marginTop: 10 }}>{EXIDX[current].n}</AppText><Chart points={topPoints} unit={S.unit} color={colors.blue} /><View style={styles.between}><AppText muted>{t('Best weight')}</AppText><AppText style={{ color: colors.accent, fontWeight: '800' }}>{fmtNum(bestWeightFor(S, current))} {S.unit}</AppText></View>{oneRm.length ? <><SectionTitle>{t('Estimated 1RM')}</SectionTitle><Chart points={oneRm} unit={S.unit} color={colors.orange} /><AppText muted>{t('Best:')} {fmtNum(best1RM(S, current)?.est)} {S.unit}</AppText></> : null}</> : <AppText muted>{t('Finish your first workout to see progress curves here.')}</AppText>}</Card>
    {S.workouts.length ? <><SectionTitle>{t('Recent workouts')}</SectionTitle>{[...S.workouts].reverse().slice(0, 6).map(workout => <Pressable key={workout.id} onPress={() => navigation.navigate('History', { workoutId: workout.id })}><Card><View style={styles.between}><View><AppText style={{ fontWeight: '800' }}>{workout.name}</AppText><AppText muted>{fmtDate(workout.d, true)} · {workout.entries.length} {t('exercises')}</AppText></View><AppText style={{ color: colors.accent, fontWeight: '700' }}>{fmtNum(workoutVolume(workout))} {S.unit}</AppText></View></Card></Pressable>)}</> : null}
  </Screen>;
}
function Tile({ icon, title, value }) { const colors = useColors(); return <Card style={styles.tile}><MaterialCommunityIcons name={icon} color={colors.accent} size={20} /><AppText muted style={{ fontSize: 11 }}>{title}</AppText><AppText style={{ fontWeight: '800', fontSize: 21 }}>{value}</AppText></Card>; }
const styles = StyleSheet.create({ tiles: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, tile: { width: '48%', gap: 5 }, cardTitle: { fontWeight: '800', fontSize: 20, marginBottom: 8 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, barRow: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 7 }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 } });
