import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import QRCode from 'react-native-qrcode-svg';
import { CameraView, Haptics, useCameraPermissions, useSoundPlayer, useWorkoutWakeLock } from '../lib/native';
import { useStore } from '../store';
import { addExerciseToActive, createActiveWorkout, finishActiveWorkout } from '../lib/workouts';
import { EFFORT, effortOf, isBw, modeOf, setLabel, setsDoneActive, supersetUnits, unitOf } from '../lib/history';
import { effectiveRoutine, lastBW } from '../lib/history';
import { allExercises, exOr } from '../lib/exercises';
import { decodeWorkoutShare, encodeWorkoutShare } from '../lib/workoutShare';
import { fmtDur, fmtNum, fmtVol, todayISO } from '../lib/format';
import { t } from '../lib/i18n';
import { useTimers } from '../timers';
import { ExerciseConfig, ExerciseDetail, ExerciseMedia, ExercisePicker } from '../components/exercises';
import BodyMap from '../components/BodyMap';
import { loadOfWorkouts } from '../lib/muscles';
import { AppText, Button, Card, Header, IconButton, Input, Progress, Screen, SectionTitle, useColors } from '../components/ui';

function Elapsed({ start }) { const [text, setText] = useState('0:00'); useEffect(() => { const tick = () => { const seconds = Math.max(0, Math.floor((Date.now() - start) / 1000)); setText(`${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`); }; tick(); const id = setInterval(tick, 1000); return () => clearInterval(id); }, [start]); return <AppText muted>{text}</AppText>; }
function ActiveWakeLock() { useWorkoutWakeLock('opengym-workout'); return null; }

export default function WorkoutScreen({ navigation, route }) {
  const { S, update } = useStore(); const active = S.active; const [summary, setSummary] = useState(null); const [startId, setStartId] = useState(undefined); const [startPlan, setStartPlan] = useState(null); const [weight, setWeight] = useState('');
  useEffect(() => { if (!active && !summary && route.params?.requestStart) { setStartId(route.params.routineId ?? null); setStartPlan(null); setWeight(String(lastBW(S)?.w || '')); navigation.setParams({ requestStart: null }); } }, [route.params?.requestStart, active, summary]);
  const begin = () => { const bodyweight = Number(weight.replace(',', '.')); if (!(bodyweight > 0)) return; update(state => { state.active = createActiveWorkout(state, startId, bodyweight, startPlan); }); setStartId(undefined); setStartPlan(null); };
  if (!active) {
    if (summary) return <FinishSummary workout={summary} onDone={() => { setSummary(null); navigation.navigate('Home'); }} />;
    return <StartChooser open={(id, plan = null) => { setStartId(id); setStartPlan(plan); setWeight(String(lastBW(S)?.w || '')); }} startId={startId} weight={weight} setWeight={setWeight} begin={begin} close={() => { setStartId(undefined); setStartPlan(null); }} />;
  }
  return <>{S.keepAwake !== false ? <ActiveWakeLock /> : null}<ActiveWorkout onFinished={setSummary} /></>;
}
function StartChooser({ open, startId, weight, setWeight, begin, close }) {
  const { S } = useStore(); const colors = useColors(); const [builder, setBuilder] = useState(false); const [scanner, setScanner] = useState(false); const [scannedPlan, setScannedPlan] = useState(null); const today = effectiveRoutine(S, todayISO()); const others = S.routines.filter(routine => routine.id !== today?.id); const knownIds = useMemo(() => new Set(allExercises(S).map(exercise => exercise.id)), [S]);
  return <Screen><Header title={t('Start workout')} subtitle={today ? t('today is {0}', today.name) : t('rest day, but no one’s stopping you')} />{today ? <Card style={{ borderColor: colors.accent }}><SectionTitle>{t("Today's plan")}</SectionTitle><AppText style={{ fontSize: 25, fontWeight: '800', marginVertical: 12 }}>{today.name}</AppText><Button title={t('Start {0}', today.name)} icon="play" primary onPress={() => open(today.id)} /></Card> : null}<SectionTitle>{t('Other routines')}</SectionTitle>{others.map(routine => <Card key={routine.id}><View style={styles.between}><View><AppText style={{ fontWeight: '800', fontSize: 18 }}>{routine.name}</AppText><AppText muted>{t('{0} exercises', routine.ex.length)}</AppText></View><Button compact title={t('Start')} onPress={() => open(routine.id)} /></View></Card>)}<SectionTitle>{t('Quick start')}</SectionTitle><Button title={t('Freestyle workout (pick as you go)')} icon="shuffle-variant" onPress={() => open(null)} /><Button title={t('Create workout to share')} icon="qrcode" onPress={() => setBuilder(true)} /><Button title={t('Scan workout QR')} icon="qrcode-scan" onPress={() => setScanner(true)} />
    <Modal transparent visible={startId !== undefined} animationType="fade" onRequestClose={close}><View style={styles.overlay}><View style={[styles.dialog, { backgroundColor: colors.surface }]}><AppText style={{ fontWeight: '800', fontSize: 22 }}>{t('Body weight')}</AppText><AppText muted>{t('Log your current weight before starting')}</AppText><Input keyboardType="decimal-pad" value={weight} onChangeText={setWeight} placeholder={S.unit} /><Button title={t('Start workout')} icon="play" primary disabled={!(Number(weight.replace(',', '.')) > 0)} onPress={begin} /><Button title={t('Cancel')} onPress={close} /></View></View></Modal>
    <ShareWorkoutBuilder visible={builder} onClose={() => setBuilder(false)} />
    <WorkoutScanner visible={scanner} knownIds={knownIds} onClose={() => setScanner(false)} onFound={plan => { setScanner(false); setScannedPlan(plan); }} />
    <ScannedPlan plan={scannedPlan} onClose={() => setScannedPlan(null)} onStart={() => { const plan = scannedPlan; setScannedPlan(null); open(null, plan); }} />
  </Screen>;
}
function ShareWorkoutBuilder({ visible, onClose }) {
  const { S } = useStore(); const colors = useColors(); const [plan, setPlan] = useState({ name: 'Shared workout', entries: [] }); const [picker, setPicker] = useState(false); const [configEx, setConfigEx] = useState(null); const [qr, setQr] = useState(null);
  useEffect(() => { if (visible) { setPlan({ name: 'Shared workout', entries: [] }); setQr(null); } }, [visible]);
  const showQr = () => { try { setQr(encodeWorkoutShare(plan)); } catch (error) { Alert.alert(t('Unable to share workout'), error.message); } };
  if (!visible) return null;
  return <Modal visible animationType="slide" onRequestClose={onClose}><Screen><Header title={t('Create workout to share')} subtitle={t('Build a plan for someone else to scan')} left={<IconButton name="close" onPress={onClose} />} /><Input value={plan.name} onChangeText={name => setPlan(value => ({ ...value, name }))} placeholder={t('Workout name')} />{plan.entries.map((entry, index) => { const exercise = exOr(entry.id); return <Card key={`${entry.id}-${index}`}><View style={styles.between}><View style={{ flex: 1 }}><AppText style={{ fontWeight: '800' }}>{exercise.n}</AppText><AppText muted>{entry.sets} {t('sets')} · {entry.mode || 'reps'}</AppText></View><IconButton name="close" accessibilityLabel={t('Remove exercise')} onPress={() => setPlan(value => ({ ...value, entries: value.entries.filter((_, itemIndex) => itemIndex !== index) }))} /></View></Card>; })}<Button title={t('Add exercise')} icon="plus" onPress={() => setPicker(true)} /><Button title={t('Share workout')} icon="qrcode" primary disabled={!plan.entries.length} onPress={showQr} />
    <ExercisePicker visible={picker} onClose={() => setPicker(false)} onPick={exercise => { setPicker(false); setConfigEx(exercise); }} /><ExerciseConfig exercise={configEx} visible={!!configEx} onClose={() => setConfigEx(null)} onSave={config => { setPlan(value => ({ ...value, entries: [...value.entries, { ...config, id: configEx.id }] })); setConfigEx(null); }} />
    <Modal transparent visible={!!qr} animationType="fade" onRequestClose={() => setQr(null)}><View style={styles.overlay}><View style={[styles.dialog, styles.qrDialog, { backgroundColor: colors.surface }]}><AppText style={{ fontWeight: '800', fontSize: 22 }}>{t('Share workout')}</AppText><AppText muted style={{ textAlign: 'center' }}>{t('Scan this code in openGym to start this workout.')}</AppText>{qr ? <View style={styles.qr}><QRCode value={qr} size={230} /></View> : null}<Button title={t('Done')} primary onPress={() => { setQr(null); onClose(); }} /></View></View></Modal>
  </Screen></Modal>;
}
function WorkoutScanner({ visible, knownIds, onClose, onFound }) {
  const colors = useColors(); const [permission, requestPermission] = useCameraPermissions(); const [scanning, setScanning] = useState(true);
  useEffect(() => { if (visible) setScanning(true); }, [visible]);
  if (!visible) return null;
  const scan = ({ data }) => { if (!scanning) return; try { onFound(decodeWorkoutShare(data, knownIds)); } catch (error) { setScanning(false); Alert.alert(t('Unable to scan workout'), error.message, [{ text: t('Try again'), onPress: () => setScanning(true) }]); } };
  return <Modal visible animationType="slide" onRequestClose={onClose}><View style={[styles.scanner, { backgroundColor: colors.bg }]}><Header title={t('Scan workout QR')} subtitle={t('Point your camera at an openGym workout QR code')} left={<IconButton name="close" onPress={onClose} />} />{!CameraView ? <Card><AppText>{t('Camera scanning is unavailable in this app build.')}</AppText></Card> : !permission?.granted ? <Card><AppText>{t('Camera permission is needed to scan a workout QR code.')}</AppText><Button title={t('Allow camera')} primary onPress={requestPermission} /></Card> : <CameraView style={styles.camera} onBarcodeScanned={scanning ? scan : undefined} barcodeScannerSettings={{ barcodeTypes: ['qr'] }} />}</View></Modal>;
}
function ScannedPlan({ plan, onClose, onStart }) {
  const colors = useColors();
  if (!plan) return null;
  return <Modal visible animationType="slide" onRequestClose={onClose}><Screen><Header title={plan.name} subtitle={t('Shared workout')} left={<IconButton name="close" onPress={onClose} />} /><Card style={{ borderColor: colors.accent }}><AppText muted>{t('Review the workout before starting.')}</AppText>{plan.entries.map((entry, index) => <View key={`${entry.id}-${index}`} style={styles.sharedEntry}><AppText style={{ fontWeight: '700' }}>{exOr(entry.id).n}</AppText><AppText muted>{entry.sets} {t('sets')} · {entry.mode || 'reps'}</AppText></View>)}</Card><Button title={t('Start workout')} icon="play" primary onPress={onStart} /><Button title={t('Cancel')} onPress={onClose} /></Screen></Modal>;
}
function FinishSummary({ workout, onDone }) {
  const { S } = useStore(); const colors = useColors(); const load = loadOfWorkouts([workout]); const muscles = new Set(Object.entries(load).filter(([, value]) => value > 0).map(([muscle]) => muscle)); const sets = workout.entries.reduce((total, entry) => total + entry.sets.filter(set => set.done).length, 0);
  return <Screen><Header title={t('Workout complete!')} subtitle={workout.name} /><Card style={styles.summaryHero}><MaterialCommunityIcons name="trophy" size={48} color={colors.accent} /><AppText style={styles.summaryTitle}>{t('Great work!')}</AppText></Card><View style={styles.summaryGrid}><Card style={styles.summaryTile}><AppText muted>{t('Duration')}</AppText><AppText style={styles.summaryValue}>{fmtDur(workout.duration || workout.end - workout.start)}</AppText></Card><Card style={styles.summaryTile}><AppText muted>{t('Volume')}</AppText><AppText style={styles.summaryValue}>{fmtVol(workout.vol, S.unit)}</AppText></Card><Card style={styles.summaryTile}><AppText muted>{t('Sets')}</AppText><AppText style={styles.summaryValue}>{sets}</AppText></Card><Card style={styles.summaryTile}><AppText muted>{t('PRs')}</AppText><AppText style={styles.summaryValue}>{workout.prs.length || '—'}</AppText></Card></View>{workout.prs.length || workout.e1prs?.length ? <Card><SectionTitle>{t('Records')}</SectionTitle>{workout.prs.map(id => <View key={id} style={styles.summaryRow}><MaterialCommunityIcons name="trophy" size={16} color={colors.accent} /><AppText>{t('New PR:')} {exOr(id).n}</AppText></View>)}{(workout.e1prs || []).map(record => <View key={record.id} style={styles.summaryRow}><MaterialCommunityIcons name="chart-line" size={16} color={colors.accent} /><AppText>{t('Best estimated 1RM:')} {exOr(record.id).n} · {fmtNum(record.est)} {S.unit}</AppText></View>)}</Card> : null}<Card><SectionTitle>{t('What you just trained')}</SectionTitle><BodyMap body={S.body} selected={muscles} /></Card><Button title={t('Nice!')} primary onPress={onDone} /></Screen>;
}
function ActiveWorkout({ onFinished }) {
  const { S, update, replaceState } = useStore(); const colors = useColors(); const { startRest, stopRest } = useTimers(); const player = useSoundPlayer(require('../../assets/beep.wav')); const [picker, setPicker] = useState(false); const [configEx, setConfigEx] = useState(null); const [detail, setDetail] = useState(null); const [work, setWork] = useState(null);
  const A = S.active; const units = supersetUnits(A.entries); const current = Math.min(A.cur, Math.max(0, A.entries.length - 1)); const unit = unitOf(units, current); const unitIndex = units.findIndex(item => item.includes(current)); const total = A.entries.reduce((sum, entry) => sum + entry.sets.length, 0); const done = setsDoneActive(A);
  const mutateEntry = (entryIndex, fn) => update(state => fn(state.active.entries[entryIndex]));
  const toggle = (entryIndex, setIndex) => {
    const wasDone = A.entries[entryIndex].sets[setIndex].done;
    mutateEntry(entryIndex, entry => { entry.sets[setIndex].done = !entry.sets[setIndex].done; });
    if (!wasDone) { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {}); if (S.sound) { player.seekTo(0); player.play(); } const entryAfter = A.entries[entryIndex]; const allEntry = entryAfter.sets.every((set, index) => index === setIndex ? true : set.done); const allWorkout = A.entries.every((entry, ei) => entry.sets.every((set, si) => ei === entryIndex && si === setIndex ? true : set.done)); if (allWorkout) stopRest(); else if (!allEntry || unit[unit.length - 1] === entryIndex) startRest(S.restSec); }
  };
  const finish = () => { if (!done) return Alert.alert(t('Nothing logged'), t('Complete at least one set first.')); Alert.alert(t('Finish workout?'), t('{0} sets completed', done), [{ text: t('Cancel') }, { text: t('Finish'), onPress: () => { const next = JSON.parse(JSON.stringify(S)); const workout = finishActiveWorkout(next); replaceState(next); stopRest(); if (S.sound) { player.seekTo(0); player.play(); } if (workout) onFinished(workout); } }]); };
  const discard = () => Alert.alert(t('Discard workout?'), t('The sets you logged in this session will be lost.'), [{ text: t('Cancel') }, { text: t('Discard'), style: 'destructive', onPress: () => { update(state => { state.active = null; }); stopRest(); } }]);
  return <Screen><Header title={A.name} subtitle={`${Math.floor(done)}/${total} ${t('sets')}`} left={<IconButton name="close" onPress={discard} />} right={<IconButton name="check" color={colors.accent} onPress={finish} />} /><View style={styles.elapsed}><Elapsed start={A.start} /><AppText muted>{unit.length > 1 ? t('Superset {0} / {1}', unitIndex + 1, units.length) : t('Exercise {0} / {1}', unitIndex + 1, units.length)}</AppText></View><Progress value={total ? done / total : 0} />
    {A.entries.length ? unit.map(entryIndex => <EntryBlock key={entryIndex} entryIndex={entryIndex} onToggle={setIndex => toggle(entryIndex, setIndex)} mutate={fn => mutateEntry(entryIndex, fn)} onDetail={() => setDetail(exOr(A.entries[entryIndex].id))} onWork={(setIndex, seconds) => setWork({ entryIndex, setIndex, seconds, started: Date.now() })} />) : <Card><AppText muted style={{ textAlign: 'center' }}>{t('Freestyle workout — add your first exercise.')}</AppText></Card>}
    <View style={styles.nav}><Button title={t('Prev')} icon="chevron-left" disabled={unitIndex <= 0} onPress={() => update(state => { state.active.cur = units[unitIndex - 1][0]; })} style={{ flex: 1 }} /><Button title={t('Next')} disabled={unitIndex < 0 || unitIndex >= units.length - 1} onPress={() => update(state => { state.active.cur = units[unitIndex + 1][0]; })} style={{ flex: 1 }} /></View><Button title={t('Add exercise')} icon="plus" onPress={() => setPicker(true)} /><Button title={done === total && total ? t('Finish workout') : t('Finish workout early')} primary={done === total && total > 0} onPress={finish} />
    <ExercisePicker visible={picker} onClose={() => setPicker(false)} onPick={exercise => { setPicker(false); setConfigEx(exercise); }} /><ExerciseConfig exercise={configEx} visible={!!configEx} onClose={() => setConfigEx(null)} onSave={config => { update(state => addExerciseToActive(state, configEx, config)); setConfigEx(null); }} /><ExerciseDetail exercise={detail} visible={!!detail} onClose={() => setDetail(null)} /><WorkTimer work={work} close={() => setWork(null)} complete={elapsed => { if (!work) return; mutateEntry(work.entryIndex, entry => { entry.sets[work.setIndex].sec = elapsed; }); if (!A.entries[work.entryIndex].sets[work.setIndex].done) toggle(work.entryIndex, work.setIndex); setWork(null); }} />
  </Screen>;
}
function EntryBlock({ entryIndex, onToggle, mutate, onDetail, onWork }) {
  const { S } = useStore(); const colors = useColors(); const entry = S.active.entries[entryIndex]; const exercise = exOr(entry.id); const mode = modeOf({ ...entry.target, id: entry.id }); const effort = EFFORT[effortOf(S)]; const bodyweight = isBw({ ...entry.target, id: entry.id });
  const change = (setIndex, key, value) => mutate(item => { item.sets[setIndex][key] = Math.max(0, Math.round(value * 10) / 10); });
  const addSet = () => mutate(item => { const last = item.sets[item.sets.length - 1] || {}; item.sets.push({ ...last, done: false }); }); const remove = () => mutate(item => { if (item.sets.length > 1) item.sets.pop(); });
  return <View style={{ gap: 10 }}><ExerciseMedia exercise={exercise} compact /><View style={styles.between}><Pressable onPress={onDetail} style={{ flex: 1 }}><AppText style={{ fontSize: 21, fontWeight: '800', textTransform: 'capitalize' }}>{exercise.n}</AppText><AppText muted style={{ textTransform: 'capitalize' }}>{exercise.tg || exercise.bp} · {exercise.eq}</AppText></Pressable><IconButton name="information-outline" onPress={onDetail} /></View>{entry.plan?.why && entry.plan.kind !== 'off' ? <Card style={{ backgroundColor: `${colors.accent}18` }}><AppText style={{ color: colors.accent, fontSize: 13 }}>{t(...entry.plan.why)}</AppText></Card> : null}<Card style={{ paddingVertical: 8 }}>{entry.sets.map((set, setIndex) => <View key={setIndex} style={[styles.setRow, { borderBottomColor: colors.border, opacity: set.done ? .55 : 1 }]}><AppText style={{ width: 22, fontWeight: '800' }}>{setIndex + 1}</AppText>{mode === 'cardio' ? <><SetField value={set.min} suffix="min" onChange={value => change(setIndex, 'min', value)} /><SetField value={set.speed} suffix="km/h" onChange={value => change(setIndex, 'speed', value)} /></> : mode === 'time' ? <><SetField value={set.sec} suffix="s" onChange={value => change(setIndex, 'sec', value)} />{!bodyweight || set.w > 0 ? <SetField value={set.w} suffix={S.unit} onChange={value => change(setIndex, 'w', value)} /> : null}<IconButton name="play" disabled={set.done} onPress={() => onWork(setIndex, set.sec || 45)} style={styles.check} /></> : <>{!bodyweight || set.w > 0 ? <SetField value={set.w} suffix={S.unit} onChange={value => change(setIndex, 'w', value)} /> : null}<SetField value={set.r} suffix="reps" onChange={value => change(setIndex, 'r', value)} />{effort ? <SetField value={set[effort.f] ?? ''} suffix={effort.hd} onChange={value => change(setIndex, effort.f, Math.min(effort.max, value))} /> : null}</>}<IconButton name={set.done ? 'check-circle' : 'checkbox-blank-circle-outline'} color={set.done ? colors.accent : colors.muted} onPress={() => onToggle(setIndex)} style={styles.check} /></View>)}<View style={styles.nav}><Button compact title={t('Remove set')} disabled={entry.sets.length <= 1} onPress={remove} style={{ flex: 1 }} /><Button compact title={t('Add set')} icon="plus" onPress={addSet} style={{ flex: 1 }} /></View></Card></View>;
}
function SetField({ value, suffix, onChange }) { const colors = useColors(); return <View style={[styles.setField, { backgroundColor: colors.surface2 }]}><TextInput keyboardType="decimal-pad" value={String(value)} onChangeText={text => onChange(Number(text.replace(',', '.')) || 0)} style={[styles.setInput, { color: colors.text }]} /><AppText dim style={{ fontSize: 9 }}>{suffix}</AppText></View>; }
function WorkTimer({ work, close, complete }) { const colors = useColors(); const [left, setLeft] = useState(0); useEffect(() => { if (!work) return undefined; setLeft(work.seconds); const id = setInterval(() => setLeft(Math.max(0, Math.ceil((work.started + work.seconds * 1000 - Date.now()) / 1000))), 250); return () => clearInterval(id); }, [work]); useEffect(() => { if (work && left === 0 && Date.now() >= work.started + work.seconds * 1000) complete(work.seconds); }, [left, work]); if (!work) return null; const elapsed = Math.max(1, work.seconds - left); return <Modal transparent visible animationType="fade"><View style={styles.overlay}><View style={[styles.dialog, { backgroundColor: colors.surface, alignItems: 'center' }]}><AppText muted>{t('Timed set')}</AppText><AppText style={{ fontSize: 64, fontWeight: '800' }}>{Math.floor(left / 60)}:{String(left % 60).padStart(2, '0')}</AppText><Button title={t('Finish set')} primary onPress={() => complete(elapsed)} style={{ width: '100%' }} /><Button title={t('Cancel')} onPress={close} style={{ width: '100%' }} /></View></View></Modal>; }
const styles = StyleSheet.create({ summaryHero: { alignItems: 'center', gap: 6, paddingVertical: 20 }, summaryTitle: { fontSize: 24, fontWeight: '800' }, summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, summaryTile: { width: '48%', gap: 4 }, summaryValue: { fontSize: 20, fontWeight: '800' }, summaryRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 8 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, elapsed: { flexDirection: 'row', justifyContent: 'space-between' }, nav: { flexDirection: 'row', gap: 8, marginTop: 6 }, setRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 6, borderBottomWidth: StyleSheet.hairlineWidth }, setField: { flex: 1, minWidth: 56, borderRadius: 9, alignItems: 'center', paddingVertical: 4 }, setInput: { minWidth: 48, textAlign: 'center', fontWeight: '800', fontSize: 17, padding: 0 }, check: { width: 38, height: 38 }, overlay: { flex: 1, backgroundColor: '#000b', justifyContent: 'center', padding: 22 }, dialog: { borderRadius: 20, padding: 18, gap: 12 }, qrDialog: { alignItems: 'center' }, qr: { padding: 12, backgroundColor: '#fff', borderRadius: 14 }, scanner: { flex: 1, padding: 16, gap: 12 }, camera: { flex: 1, minHeight: 360, borderRadius: 20, overflow: 'hidden' }, sharedEntry: { paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#8886' } });
